name: CI
on: [pull_request]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: yarn install, build
        run: |
          yarn install
          yarn run build

      - name: run Lighthouse CI
        run: |
          yarn lhci autorun
      - name: Check if JSON report exists
        run: |
          # 检查是否存在 lighthouse_report.json 文件
          if [ -f "lighthouse_report.json" ]; then
            echo "JSON report exists"
          else
            echo "JSON report does not exist"
            # 可以选择在此处添加一些逻辑来处理文件不存在的情况
          fi

      - name: Read Lighthouse report
        id: read-report
        run: echo "::set-output name=report::$(cat lighthouse_report.json)"

      - name: Add information to PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TEST }}
          script: |
            const message = `Lighthouse Report: \n${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/blob/${process.env.GITHUB_SHA}/lighthouse_report.json`;
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })

# Path: .github/workflows/lighthouse.yml
